version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: goat_db
    networks:
      - app-network # Network တစ်ခု သတ်မှတ်ပေးပါ
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goat_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d goat_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app: # ဒီနေရာမှာ သင့် App အတွက် ထည့်ပေးရပါမယ်
    build: .
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/goat_db

networks:
  app-network:
    driver: bridge
