name: Node.js CI

on: [push, pull_request] # Code Push လုပ်တိုင်း (သို့) Pull Request လုပ်တိုင်း Run မယ်

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm test
