name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      # Database အဆင်သင့်ဖြစ်သည်အထိ စောင့်ရန်
      - name: Wait for database
        run: |
          echo "Waiting for database..."
          # docker compose exec db ထဲမှာ run တာဖြစ်လို့ localhost ကိုပဲ သုံးပါ
          docker compose exec -T db pg_isready -h localhost -p 5432 -U user

      - name: Run migrations
        run: docker compose exec -T app npx knex migrate:latest --env test

      - name: Run tests
        # run: docker compose exec -T app npm test
        run: docker compose exec -e DB_HOST=db -e DB_USER=user -e DB_PASSWORD=password -e DB_NAME=goat_db app npm test
